Repository cylc/cylc-rose, pull requests merged in 2021-05, with the labels that each got.

#53 Fix: FCM Make and Rose Prune
  cylc/rose/platform_utils.py
  tests/functional/test_rose_stem.py
  tests/test_platform_utils.py
Labels: enhancement

#60 updated error msg in test
  tests/functional/test_pre_configure.py
Labels: bug

#61 Fix sphinx reference
  cylc/rose/__init__.py
Labels: small
