Repository cylc/cylc-rose, pull requests merged in 2021-08, with the labels that each got.

#74 Add mailmap
  .mailmap
Labels: small

#77 disabled capturing of stderr to allow us to see cause of failure in functional tests
  pytest.ini
Labels: enhancement

#79 check CONTRIBUTING.md against mailmap
  .github/workflows/1_create_release_pr.yml
  .github/workflows/shortlog.yml
  CONTRIBUTING.md
Labels: enhancement, small

#84 Replace `parse_workflow_arg` with `parse_reg`.
  cylc/rose/platform_utils.py
  tests/functional/test_pre_configure.py
Labels: bug, small
