Repository cylc/cylc-rose, pull requests merged in 2022-08, with the labels that each got.

#159 Bump dev version
  cylc/rose/__init__.py
Labels: small

#160 Update codecov config + add dependabot config
  .codecov.yml
  .github/dependabot.yml
  .github/workflows/tests.yml
Labels: infrastructure

#165 GH Actions bump dependencies
  .github/workflows/1_create_release_pr.yml
  .github/workflows/2_auto_publish_release.yml
  .github/workflows/shortlog.yml
  .github/workflows/tests.yml
  .github/workflows/update_copyright.yml
Labels: infrastructure, dependencies

#166 Unset environment variable set in doctests.
  cylc/rose/utilities.py
Labels: small

#167 Improve test cleanup
  tests/conftest.py
  tests/functional/test_rose_stem.py
Labels: small

#173 Bump cylc-flow dependency
  setup.cfg
Labels: small, dependencies

#171 Don't pass rose variables with state ! or !! to Cylc.
  CHANGES.md
  cylc/rose/utilities.py
  tests/functional/test_validate_no_rose_ignore_items.py
Labels: bug
