Repository cylc/cylc-rose, pull requests merged in 2022-10, with the labels that each got.

#190 GH Actions: auto bump dev version on release
  .github/workflows/2_auto_publish_release.yml
Labels: small, infrastructure

#181 Improve rose stem coverage
  cylc/rose/stem.py
  tests/functional/test_rose_stem.py
  tests/unit/test_rose_stem_units.py
Labels: technical debt

#180 feature: stem installs to workflow name not `rose-stem`
  CHANGES.md
  cylc/rose/__init__.py
  cylc/rose/stem.py
  tests/unit/test_rose_stem_units.py
Labels: enhancement

#192 Allow change of templating language when reinstalling
  CHANGES.md
  cylc/rose/entry_points.py
  cylc/rose/utilities.py
  tests/functional/test_reinstall.py
  tests/unit/test_config_tree.py
Labels: bug
