Repository cylc/cylc-rose, pull requests merged in 2022-09, with the labels that each got.

#172 Rose Stem Fixes
  CHANGES.md
  cylc/rose/stem.py
  tests/functional/test_rose_stem.py
  tests/unit/test_rose_stem_units.py
Labels: bug

#186 Fix changelog conflict with 1.1.x
  CHANGES.md
Labels: small

#175 Bump dev version on master to next minor release
  cylc/rose/__init__.py
Labels: small

#179 Review rose stem docs
  cylc/rose/stem.py
Labels: documentation

#187 Bump rose dependency to `2.1.*`
  setup.cfg
Labels: small
