Repository cylc/cylc-rose, pull requests merged in 2023-07, with the labels that each got.

#231 Permitted warnings about root-dir for all versions of Cylc.
  CHANGES.md
  cylc/rose/utilities.py
  tests/conftest.py
  tests/functional/test_pre_configure.py
  tests/unit/test_config_node.py
Labels: bug, small

#240 Add missing dependency on ansimarkup
  setup.cfg
Labels: small, dependencies

#241 Bump dev version
  cylc/rose/__init__.py
Labels: small
