Repository cylc/cylc-rose, pull requests merged in 2023-12, with the labels that each got.

#270 Fix linter objections to expression tuples.
  tests/unit/test_platform_utils.py
Labels: small

#271 GH Actions: separate lint vs test jobs
  .github/workflows/branch_sync.yml
  .github/workflows/tests.yml
  setup.cfg
  tests/functional/test_rose_stem.py
Labels: infrastructure

#275 Tests and stuff
  .github/workflows/tests.yml
  tests/functional/test_rose_stem.py
Labels: small, infrastructure
