Repository cylc/cylc-rose, pull requests merged in 2024-02, with the labels that each got.

#294 use fqdn in rose-stem tests
  tests/functional/test_rose_stem.py
Labels: small

#269 Repopulate cached GlobalConfig object if CYLC_SYMLINKS exported to env.
  CHANGES.md
  cylc/rose/__init__.py
  cylc/rose/utilities.py
  tests/conftest.py
  tests/functional/test_ROSE_ORIG_HOST.py
  tests/functional/test_reinstall.py
  tests/functional/test_reinstall_clean.py
  tests/functional/test_rose_fileinstall.py
  tests/functional/test_utils.py
Labels: enhancement

#276 fileinstall: remove asyncio logic
  cylc/rose/entry_points.py
  cylc/rose/fileinstall.py
  cylc/rose/stem.py
  setup.cfg
  tests/conftest.py
  tests/functional/test_ROSE_ORIG_HOST.py
  tests/functional/test_pre_configure.py
  tests/functional/test_reinstall.py
  tests/functional/test_reinstall_clean.py
  tests/functional/test_reinstall_fileinstall.py
  tests/functional/test_rose_fileinstall.py
  tests/functional/test_rose_stem.py
  tests/functional/test_utils.py
  tests/unit/test_fileinstall.py
Labels: bug

#298 tests: fix flaky text
  cylc/rose/jinja2_parser.py
Labels: small
